# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{duns-lookup}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kali Donovan"]
  s.date = %q{2010-05-10}
  s.description = %q{Provides a small wrapper around the Dun & Bradstreet website to retrieve business information from DUNS numbers.}
  s.email = %q{kali@deviantech.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "doc/classes/Duns.html",
     "doc/classes/Duns.src/M000001.html",
     "doc/classes/Duns.src/M000002.html",
     "doc/classes/Duns.src/M000003.html",
     "doc/classes/Duns.src/M000004.html",
     "doc/classes/Duns.src/M000005.html",
     "doc/classes/Duns.src/M000006.html",
     "doc/classes/DunsError.html",
     "doc/created.rid",
     "doc/files/lib/duns-lookup_rb.html",
     "doc/fr_class_index.html",
     "doc/fr_file_index.html",
     "doc/fr_method_index.html",
     "doc/index.html",
     "doc/rdoc-style.css",
     "duns-lookup.gemspec",
     "lib/duns-lookup.rb",
     "spec/duns-lookup_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/kdonovan/duns-lookup}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Wrapper for looking up Dun & Bradstreet numbers (DUNS)}
  s.test_files = [
    "spec/duns-lookup_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<mechanize>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<mechanize>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<mechanize>, [">= 0"])
  end
end

