# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "duns-lookup"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kali Donovan"]
  s.date = "2011-09-19"
  s.description = "Provides a small wrapper around the Dun & Bradstreet website to retrieve business information from DUNS numbers."
  s.email = "kali@deviantech.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "doc/classes/Duns.html",
    "doc/classes/Duns.src/M000001.html",
    "doc/classes/Duns.src/M000002.html",
    "doc/classes/Duns.src/M000003.html",
    "doc/classes/Duns.src/M000004.html",
    "doc/classes/Duns.src/M000005.html",
    "doc/classes/Duns.src/M000006.html",
    "doc/classes/DunsError.html",
    "doc/created.rid",
    "doc/files/lib/duns-lookup_rb.html",
    "doc/fr_class_index.html",
    "doc/fr_file_index.html",
    "doc/fr_method_index.html",
    "doc/index.html",
    "doc/rdoc-style.css",
    "duns-lookup.gemspec",
    "lib/duns-lookup.rb",
    "spec/duns-lookup_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/kdonovan/duns-lookup"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Wrapper for looking up Dun & Bradstreet numbers (DUNS)"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<mechanize>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<mechanize>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<mechanize>, [">= 0"])
  end
end

